project 'JHButton.xcodeproj'
# Uncomment the next line to define a global platform for your project

target 'JHButton' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
   platform :ios, '9.0'
   inhibit_all_warnings!

  # Pods for JHButton
  #UI布局
   pod 'Masonry'
end

target 'JHButton_Swift' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
   platform :ios, '10.0'
   inhibit_all_warnings!
  # Pods for JHButton
  #UI布局
   pod 'SnapKit'
end
