project 'JHButton.xcodeproj'

# Uncomment the next line to define a global platform for your project
  platform :ios, '8.0'
  inhibit_all_warnings! 
target 'JHButton' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for JHButton
  #UI布局
   pod 'Masonry'
end
